modLoader = "javafml"
loaderVersion = "[25,)"

issueTrackerURL = "${mod_issues_url}"
license = "${mod_license}"
clientSideOnly = true

[[mods]]
authors = "${mod_authors}"
description = '''${mod_description}'''
displayName = "${mod_name}"
logoFile = "icon.png"
modId = "${mod_id}"
version = "${mod_version}"
displayTest = "NONE"

[[dependencies.${mod_id}]]
modId = "forge"
ordering = "NONE"
side = "BOTH"
mandatory = true
versionRange = "[25,)"

[[dependencies.${mod_id}]]
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
mandatory = true
versionRange = "[1.13.2,1.16.5]"

[[mixins]]
config = "${mod_id}.mixins.json"