modLoader = "javafml"
loaderVersion = "[1,)"

issueTrackerURL = "${mod_issues_url}"
license = "${mod_license}"

[[mods]]
authors = "${mod_authors}"
description = '''${mod_description}'''
displayName = "${mod_name}"
logoFile = "icon.png"
modId = "${mod_id}"
version = "${mod_version}"

[[dependencies.${mod_id}]]
modId = "neoforge"
ordering = "NONE"
side = "BOTH"
mandatory = true
versionRange = "[1,)"

[[dependencies.${mod_id}]]
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
mandatory = true
versionRange = "[1.20.2,)"

[[mixins]]
config = "${mod_id}.mixins.json"